runtime: python311
instance_class: F2

env_variables:
  FLASK_ENV: "production"
  FLASK_DEBUG: "false"
  FLASK_HOST: "127.0.0.1"
  FLASK_PORT: "8080"  # App Engine uses port 8080
  DB_USER: "postgres"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_HOST: "/cloudsql/${INSTANCE_CONNECTION_NAME}"
  DB_PORT: "5432"
  DB_NAME: "sportconnect"
  JWT_SECRET_KEY: "${JWT_SECRET_KEY}"

beta_settings:
  cloud_sql_instances: ${INSTANCE_CONNECTION_NAME}

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /static/(.*)
  static_dir: static/\1
  secure: always

- url: /.*
  script: auto
  secure: always 