version: '3.8'

services:
  web:
    image: my-flask-app
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/sportConnectBack
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
