name: CI/CD Flask + Postgres

on:
  push:
    branches: [ "master" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t my-flask-app .

      - name: Launch with Docker Compose
        env:
          DB_USER: postgres
          DB_PASSWORD: admin
          DB_NAME: sportConnectBack
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: |
          # Démarrer en mode détaché mais capturer les logs
          docker compose up -d
          
          # Attendre que le conteneur Flask soit healthy
          timeout 60 bash -c 'until docker inspect flask-app --format "{{.State.Health.Status}}" | grep healthy; do sleep 3; done' || \
          (docker logs flask-app && exit 1)
          
          # Afficher les logs initiaux pour debug
          docker logs flask-app

      - name: Verify environment
        run: |
          echo "=== Variables dans Flask ==="
          docker exec flask-app sh -c 'env | grep -E "DB_|SECRET_|JWT"'
          
          echo "=== Test de connexion DB ==="
          docker exec flask-app python -c "
          import os;
          print(f\"Connexion à : postgresql://{os.getenv('DB_USER')}:****@{os.getenv('DB_HOST')}:5432/{os.getenv('DB_NAME')}\")
          "

      - name: Test API endpoint
        run: |
          curl -v http://localhost:5000/sport/

      - name: Cleanup after tests
        if: always()
        run: |
          docker compose down -v  

      # Étape de déploiement avec l'URL exacte du dépôt
      - name: Deploy to EC2
        if: success() && github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Installation des prérequis
            sudo apt-get update || sudo yum update -y
            
            # Installation de Git si nécessaire
            which git || sudo apt-get install -y git || sudo yum install -y git
            
            # Installation de Docker et Docker Compose si nécessaires
            which docker || { 
              sudo apt-get install -y docker.io || sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
            }
            
            which docker-compose || sudo which docker-compose || {
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              sudo ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
            }
            
            # 2. Créer le répertoire du projet 
            mkdir -p ~/app
            cd ~/app
            
            # 3. Cloner ou mettre à jour le dépôt avec l'URL exacte
            if [ -d ".git" ]; then
              git fetch --all
              git reset --hard origin/master
            else
              # URL exacte du dépôt
              git clone https://github.com/ahmeddahdouh/backendSportConnect.git .
            fi
            
            # 4. Configuration des variables d'environnement
            cat > .env << EOL
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            EOL
        
            # 5. Construire et démarrer les conteneurs
            sudo docker compose down || true
            
            # Vérifier si docker compose ou docker-compose est disponible
            if command -v docker-compose &> /dev/null; then
              sudo docker-compose build
              sudo docker-compose up -d
            else
              sudo docker compose build
              sudo docker compose up -d
            fi
            
            # 6. Vérifier l'état après un délai
            sleep 30
            sudo docker ps
            curl -v http://localhost:5000/sport/ || echo "L'API n'est pas encore accessible"