name: Deploy to Dev Environment

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: dev-backend
  REGION: europe-west1
  DB_INSTANCE: ${{ secrets.DB_INSTANCE_DEV }}
  DB_USER: "postgres"
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: "sportconnect"

jobs:
  deploy:
    name: Deploy to Dev
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Cloud SDK
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Get instance connection name
      id: get-connection-name
      run: |
        INSTANCE_CONNECTION_NAME=$(gcloud sql instances describe ${{ env.DB_INSTANCE }} --format='value(connectionName)')
        echo "INSTANCE_CONNECTION_NAME=$INSTANCE_CONNECTION_NAME" >> $GITHUB_ENV

    - name: Run database migrations
      run: |
        # Run migrations using Cloud SQL Auth proxy
        wget https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.1.2/cloud-sql-proxy.linux.amd64 -O cloud-sql-proxy
        chmod +x cloud-sql-proxy
        
        # Start Cloud SQL Auth proxy in the background
        ./cloud-sql-proxy ${{ env.INSTANCE_CONNECTION_NAME }} --port 5432 &
        
        # Wait for the proxy to start
        sleep 5
        
        # Set environment variables for Alembic
        export DB_HOST="localhost"
        export DB_PORT="5432"
        
        # Run migrations
        alembic upgrade head

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --project ${{ env.PROJECT_ID }} --version dev --quiet 